name: Automerge labelled PR
on:
    pull_request:
        types: [labeled]
        branches: [master]
jobs:
    automerge:
        runs-on: ubuntu-latest
        steps:
            - name: Automatically Merge PR
              uses: plm9606/automerge_actions@1.2.3
              with:
                  reviewers-number: 0
                  auto-delete: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
