name: gssoc

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.comment.body, 'base branch') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Hi, this is github bot and I'll assist you if you have any doubts regarding changing the base branch. Refer to this [image](https://media.discordapp.net/attachments/818844424292794448/819192791276060742/Screenshot_20210126-095421__01__01.png?width=884&height=612) to change base branch."
