name: hello-world

on:
    push:
        branches:
            - master
            # - 'feature/pranav/*'
        tags:
            - hello
            - hello.*
        paths:
            # paths-ignore:
            - '**.js'

        # branches-ignore:
        #     - develop

        # [push]

        # repository_dispatch:
        #   type: [build]

        # schedule:
        #   - cron: '0 5 * * *'
        #   - cron: '9 15 * * 6'

jobs:
    run-commands:
        runs-on: ubuntu-latest
        steps:
            - name: hello-world
              run: echo "hello world"
            - name: node-commands
              run: |
                  node -v
                  npm -v
