name: hello-world

on: [push]

jobs:
    run-commands:
        runs-on: ubuntu-latest
        steps:
            - name: hello-world
              run: echo "hello world"
            - name: node-commands
              run: |
                  node -v
                  npm -v
