name: js-action

on:
    push:
    pull_request:
        types: [opened, closed, assigned, reopened]

jobs:
    run-js-action:
        runs-on: ubuntu-latest
        steps:
            - name: greeting action
              id: greet
              uses: actions/hello-world-javascript-action@main
              with:
                  who-to-greet: 'Pranav'
            - name: log greet time
              run: '${{ steps.greet.outputs.time }}'
            - name: log email
              run: '${{ github.event.client_payload.commits[0].author.email }}'
