name: js-action

on: [push]

jobs:
    run-js-action:
        runs-on: ubuntu-latest
        steps:
            - name: greeting action
              id: greet
              uses: actions/hello-world-javasript-action@v1.1
              with:
                  who-to-greet: Pranav
            - name: log greet time
              run: '${{ steps.greet.outputs.time }}'
